apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-api.fullname" . }}
  labels:
    app: {{ include "event-api.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "event-api.name" . }}
