spring:
  application:
    name: ticketera

  datasource:
    username: ticketera
    password: dGVzdGRi
    url: jdbc:postgresql://localhost:5432/ticketera
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  flyway:
    user: ticketera
    password: dGVzdGRi
    url: jdbc:postgresql://localhost:5432/ticketera


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

#
#logging:
#  level:
#    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG