server:
  port: 8082
spring:
  application:
    name: ticketera

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/ticketera
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  flyway:
    user: user
    password: password
    url: jdbc:postgresql://localhost:5432/ticketera


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
aws:
  accessKey: ACCESS_KEY
  secretKey: SECRET_KEY
  region: us-east-1
  bucket: bucket-name

#
#logging:
#  level:
#    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG