apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-api
  namespace: event-api  
  labels:
    app: event-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-api
  template:
    metadata:
      labels:
        app: event-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: event-api
          image: ghcr.io/leandrodalbo/event-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
