apiVersion: v1
kind: Service
metadata:
  name: event-api
  namespace: event-api   
spec:
  selector:
    app: event-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
