name: Build and Test

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build and Test
        run: ./gradlew clean build test --no-daemon
