name: Build and Publish Docker image to GitHub 

on:
  push:
    branches:
      - main 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: leandrodalbo/opustix-api 
  VERSION: latest

jobs:
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}